version: "3.8"
services:
    monorepo-js:
    build:
        context: .
        dockerfile: dockerfile
    container_name: monorepo-js
    ports:
        - "3000:8000"
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        start_period: 20s
        interval: 30s
        timeout: 10s
        retries: 5
